### ISSUE TITLE
Reversed mode

### ISSUE THREAD

**Issue by PavelAmialiushka** [zarly/alfa-dictionary#4]
Можно ли создать реверсный режим? Т.е. помечать и запоминать неизвестные слова. 

Т.е. сценарий такой: открываю страницу, читаю и помечаю слова, которых я не знаю. Затем экспортирую список слов желательно с переводом в программы типа Anki

**Comment by zarly** [comment]
Такой функционал и так предоставляют большинство переводчиков, это приложение создавалось с прямо противоположной целью.
